genome: test
ensembl_genome_build: 113
strand: reverse # check https://pypi.org/project/TEtranscripts/

fdr_cutoff: 0.05 # cut off for volcano plots
fc_cutoff: 0.5 # log2 fold change cut off for volcano plots

spike_in:
  apply: False # whether to apply spike-in correction
  name: ERCC- # pattern for spike-in names
  gtf: /path/to/ERCC.gtf
  fasta: /path/to/ERCC.fasta

mapping: # STAR mapping parameters
  outFilterMultimapNmax: "100"
  winAnchorMultimapNmax: "100"
  extra_params : "" # additional arguments to pass to STAR

# Split bam files by chromosome for parallel processing of each sample
# This is recommended for running large datasets on a cluster
split_bam: False

deeptools:
  normalisation: RPKM
  binsize: 1000

resources: # computing resources
  trim:
    cpu: 8
    time: 60
  fastqc:
    cpu: 4
    time: 60
  mapping:
    cpu: 10
    time: 120
  samtools:
    cpu: 4
    time: 30
  deeptools:
    cpu: 6
    time: 60
  deseq2:
    cpu: 6
    time: 60 
  plotting:
    cpu: 2
    time: 20
